import type {
  TenantStore,
  RemoteLogEntry,
  StaffAuditLog,
  ProvisioningRequest,
  TenantInvoice,
  DatabaseBackupJob,
  ClientAppRolloutStatus,
  SaaSFinanceOverview,
} from '../../types/fleet'

export const INITIAL_INVOICES: TenantInvoice[] = [
  {
    id: 'inv-2026-001',
    invoiceNumber: 'INV/2026/10/001',
    tenantId: 'org-resto',
    tenantName: 'Nusantara Bistro',
    planTier: 'enterprise',
    billingCycle: 'annually',
    amount: 19990000,
    status: 'paid',
    issuedAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    dueDate: Date.now() - 1000 * 60 * 60 * 24 * 23,
    paidAt: Date.now() - 1000 * 60 * 60 * 24 * 28,
    paymentMethod: 'va_bca',
    items: [
      {
        description: 'Paket Enterprise (1 Tahun / 12 Bulan)',
        quantity: 1,
        unitPrice: 19990000,
        subtotal: 19990000,
      },
    ],
    notes: 'Pembayaran tahunan lunas via Virtual Account BCA Korporat.',
  },
  {
    id: 'inv-2026-002',
    invoiceNumber: 'INV/2026/10/002',
    tenantId: 'tenant-fine-dining',
    tenantName: 'Mori Japanese Dining & Izakaya',
    planTier: 'enterprise',
    billingCycle: 'annually',
    amount: 21190000,
    status: 'paid',
    issuedAt: Date.now() - 1000 * 60 * 60 * 24 * 45,
    dueDate: Date.now() - 1000 * 60 * 60 * 24 * 38,
    paidAt: Date.now() - 1000 * 60 * 60 * 24 * 42,
    paymentMethod: 'va_mandiri',
    items: [
      {
        description: 'Paket Enterprise (1 Tahun)',
        quantity: 1,
        unitPrice: 19990000,
        subtotal: 19990000,
      },
      {
        description: 'Add-on Dedicated KDS Cloud Stream (1 Tahun)',
        quantity: 1,
        unitPrice: 1200000,
        subtotal: 1200000,
      },
    ],
    notes: 'Perpanjangan kontrak tahun ke-2 Mori Boga Sukses.',
  },
  {
    id: 'inv-2026-003',
    invoiceNumber: 'INV/2026/10/003',
    tenantId: 'tenant-kopi-artisan',
    tenantName: 'Kopi Titik Temu & Roastery',
    planTier: 'pro',
    billingCycle: 'monthly',
    amount: 949000,
    status: 'pending',
    issuedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    dueDate: Date.now() + 1000 * 60 * 60 * 24 * 5, // Due in 5 days
    paymentMethod: 'qris',
    items: [
      {
        description: 'Paket Pro Bulanan (Periode Oktober - November 2026)',
        quantity: 1,
        unitPrice: 799000,
        subtotal: 799000,
      },
      {
        description: 'Add-on 1 Extra Cabang (Cabang Kemang)',
        quantity: 1,
        unitPrice: 150000,
        subtotal: 150000,
      },
    ],
    notes: 'Tagihan rutin bulanan. Menunggu verifikasi settlement QRIS dinamis.',
  },
  {
    id: 'inv-2026-004',
    invoiceNumber: 'INV/2026/10/004',
    tenantId: 'tenant-bakmi-nusantara',
    tenantName: 'Bakmi Warisan 1982',
    planTier: 'pro',
    billingCycle: 'monthly',
    amount: 799000,
    status: 'overdue',
    issuedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    dueDate: Date.now() - 1000 * 60 * 60 * 24 * 2, // 2 days past due!
    paymentMethod: 'manual_transfer',
    items: [
      {
        description: 'Paket Pro Bulanan (Perpanjangan Lisensi Kasir)',
        quantity: 1,
        unitPrice: 799000,
        subtotal: 799000,
      },
    ],
    notes: 'Jatuh tempo terlewati. Akun masuk masa tenggang (Grace Period 3 hari).',
  },
  {
    id: 'inv-2026-005',
    invoiceNumber: 'INV/2026/10/005',
    tenantId: 'tenant-grab-booth',
    tenantName: 'Kopi Booth Express Sudirman',
    planTier: 'starter',
    billingCycle: 'monthly',
    amount: 299000,
    status: 'pending',
    issuedAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    dueDate: Date.now() + 1000 * 60 * 60 * 24 * 11, // Due in 11 days
    paymentMethod: 'qris',
    items: [
      {
        description: 'Aktivasi Paket Starter Paska Trial 14 Hari',
        quantity: 1,
        unitPrice: 299000,
        subtotal: 299000,
      },
    ],
    notes: 'Konversi akun dari masa uji coba gratis.',
  },
  {
    id: 'inv-2026-006',
    invoiceNumber: 'INV/2026/09/014',
    tenantId: 'tenant-kopi-artisan',
    tenantName: 'Kopi Titik Temu & Roastery',
    planTier: 'pro',
    billingCycle: 'monthly',
    amount: 799000,
    status: 'paid',
    issuedAt: Date.now() - 1000 * 60 * 60 * 24 * 32,
    dueDate: Date.now() - 1000 * 60 * 60 * 24 * 25,
    paidAt: Date.now() - 1000 * 60 * 60 * 24 * 26,
    paymentMethod: 'va_bca',
    items: [
      {
        description: 'Paket Pro Bulanan (September 2026)',
        quantity: 1,
        unitPrice: 799000,
        subtotal: 799000,
      },
    ],
    notes: 'Pembayaran bulan lalu lunas.',
  },
]

export const INITIAL_BACKUPS: DatabaseBackupJob[] = [
  {
    id: 'bkp-resto-001',
    tenantId: 'org-resto',
    tenantName: 'Nusantara Bistro',
    snapshotSizeMb: 48.2,
    totalRecordsCount: 14820,
    status: 'completed',
    createdAt: Date.now() - 1000 * 60 * 60 * 4,
    checksum: 'sha256:7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c',
    retentionDays: 90,
  },
  {
    id: 'bkp-mori-002',
    tenantId: 'tenant-fine-dining',
    tenantName: 'Mori Japanese Dining & Izakaya',
    snapshotSizeMb: 32.6,
    totalRecordsCount: 9420,
    status: 'completed',
    createdAt: Date.now() - 1000 * 60 * 60 * 6,
    checksum: 'sha256:3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d',
    retentionDays: 90,
  },
  {
    id: 'bkp-titik-003',
    tenantId: 'tenant-kopi-artisan',
    tenantName: 'Kopi Titik Temu & Roastery',
    snapshotSizeMb: 18.4,
    totalRecordsCount: 5210,
    status: 'completed',
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
    checksum: 'sha256:9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c',
    retentionDays: 30,
  },
  {
    id: 'bkp-bakmi-004',
    tenantId: 'tenant-bakmi-nusantara',
    tenantName: 'Bakmi Warisan 1982',
    snapshotSizeMb: 24.1,
    totalRecordsCount: 6840,
    status: 'completed',
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
    checksum: 'sha256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
    retentionDays: 30,
  },
]

export const INITIAL_ROLLOUTS: ClientAppRolloutStatus[] = [
  {
    version: 'v2.5.0-prod',
    releaseChannel: 'production',
    isLatest: true,
    releaseDate: '2026-10-06',
    activeTenantsCount: 4,
    activeTerminalsCount: 14,
    adoptionPct: 87.5,
    notes: 'Hotfix printer ESC/POS cut buffer & IndexedDB auto-vacuuming.',
  },
  {
    version: 'v2.4.2-stable',
    releaseChannel: 'canary',
    isLatest: false,
    releaseDate: '2026-09-22',
    activeTenantsCount: 1,
    activeTerminalsCount: 1,
    adoptionPct: 12.5,
    notes: 'Versi legacy pada terminal kasir Pasar Baru (Bakmi Warisan).',
  },
]

export const INITIAL_TENANTS: TenantStore[] = [
  {
    id: 'org-resto',
    slug: 'nusantara-bistro',
    name: 'Nusantara Bistro',
    legalName: 'PT Nusantara Boga Kuliner',
    ownerName: 'Budi Pratama',
    ownerPhone: '+62 812-8877-6655',
    ownerEmail: 'owner@nusantarabistro.id',
    subscriptionTier: 'enterprise',
    billingStatus: 'active',
    billingCycle: 'annually',
    monthlyFee: 1999000,
    lifetimePaid: 39980000,
    autoRenew: true,
    subscriptionValidUntil: Date.now() + 1000 * 60 * 60 * 24 * 180, // 180 days
    maxOutlets: 10,
    maxTerminals: 25,
    healthStatus: 'healthy',
    liveStoreUrl: 'https://fnb-erp.vercel.app',
    activeOutlets: [
      {
        id: 'out-senopati',
        name: 'Cabang Senopati',
        code: 'SENO',
        activeTerminalsCount: 3,
        printerHealth: 'ok',
        todayGmv: 4850000,
        todayOrdersCount: 42,
      },
      {
        id: 'out-dago',
        name: 'Cabang Dago',
        code: 'DAGO',
        activeTerminalsCount: 2,
        printerHealth: 'ok',
        todayGmv: 3200000,
        todayOrdersCount: 28,
      },
      {
        id: 'hq',
        name: 'Kantor Pusat & Central Kitchen',
        code: 'HQ',
        activeTerminalsCount: 1,
        printerHealth: 'ok',
        todayGmv: 0,
        todayOrdersCount: 0,
      },
    ],
    latestTelemetry: {
      devices: [
        {
          deviceId: 'dev-seno-pos1',
          name: 'iPad Pro Kasir Utama Senopati',
          deviceType: 'pos_tablet',
          outletId: 'out-senopati',
          os: 'iPadOS 17.4',
          browser: 'Mobile Safari 17.4',
          screenResolution: '2048x1536',
          batteryLevel: 94,
          isCharging: true,
          networkLatencyMs: 24,
          lastHeartbeatAt: Date.now() - 1000 * 45,
          appVersion: 'v2.5.0-prod',
        },
        {
          deviceId: 'dev-seno-kds1',
          name: 'Display Dapur Kitchen Senopati',
          deviceType: 'kds_display',
          outletId: 'out-senopati',
          os: 'Android 13.0',
          browser: 'Chrome 122.0',
          screenResolution: '1920x1080',
          networkLatencyMs: 18,
          lastHeartbeatAt: Date.now() - 1000 * 20,
          appVersion: 'v2.5.0-prod',
        },
        {
          deviceId: 'dev-dago-pos1',
          name: 'Samsung Tab S8 Kasir Dago',
          deviceType: 'pos_tablet',
          outletId: 'out-dago',
          os: 'Android 14.0',
          browser: 'Chrome 124.0',
          screenResolution: '2560x1600',
          batteryLevel: 68,
          isCharging: false,
          networkLatencyMs: 35,
          lastHeartbeatAt: Date.now() - 1000 * 60,
          appVersion: 'v2.5.0-prod',
        },
      ],
      printers: [
        {
          printerId: 'prn-seno-main',
          outletId: 'out-senopati',
          name: 'Epson TM-T82III LAN Kasir Senopati',
          connectionType: 'network',
          paperWidth: '80mm',
          status: 'connected',
          lastPrintJobAt: Date.now() - 1000 * 180,
          failedJobsCount: 0,
        },
      ],
      storage: {
        outletId: 'out-senopati',
        localStorageBytes: 420000,
        estimatedQuotaBytes: 5242880,
        unSyncedTransactionsCount: 0,
        integrityOk: true,
        lastSyncAt: Date.now() - 1000 * 120,
      },
    },
    modules: {
      pos_quick_service: true,
      pos_dine_in_tables: true,
      kitchen_routing_kds: true,
      inventory_basic: true,
      inventory_recipes_hpp: true,
      multi_warehouse_transfer: true,
      batch_production_roasting: true,
      b2b_wholesale_invoicing: true,
      accurate_grade_accounting: true,
      fixed_assets: true,
      bank_reconciliation: true,
      live_excel_export: true,
      official_pdf_export: true,
    },
    emergencyMaintenance: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
    updatedAt: Date.now(),
  },
  {
    id: 'tenant-kopi-artisan',
    slug: 'kopi-titik-temu',
    name: 'Kopi Titik Temu & Roastery',
    legalName: 'CV Titik Temu Rasa Indonesia',
    ownerName: 'Dimas Wijaya',
    ownerPhone: '+62 813-1122-3344',
    ownerEmail: 'dimas@titiktemu.id',
    subscriptionTier: 'pro',
    billingStatus: 'active',
    billingCycle: 'monthly',
    monthlyFee: 949000, // Pro + 1 extra outlet
    lifetimePaid: 3946000,
    autoRenew: true,
    subscriptionValidUntil: Date.now() + 1000 * 60 * 60 * 24 * 45,
    maxOutlets: 3,
    maxTerminals: 6,
    healthStatus: 'warning',
    liveStoreUrl: 'https://fnb-erp.vercel.app?tenant=titik-temu',
    activeOutlets: [
      {
        id: 'out-barito',
        name: 'Cabang Barito',
        code: 'BARI',
        activeTerminalsCount: 2,
        printerHealth: 'issue',
        todayGmv: 2750000,
        todayOrdersCount: 56,
      },
      {
        id: 'out-kemang',
        name: 'Cabang Kemang',
        code: 'KMNG',
        activeTerminalsCount: 1,
        printerHealth: 'ok',
        todayGmv: 1890000,
        todayOrdersCount: 38,
      },
    ],
    latestTelemetry: {
      devices: [
        {
          deviceId: 'dev-barito-pos',
          name: 'iPad 10th Gen Kasir Barito',
          deviceType: 'pos_tablet',
          outletId: 'out-barito',
          os: 'iPadOS 17.2',
          browser: 'Mobile Safari 17.2',
          screenResolution: '2360x1640',
          batteryLevel: 42,
          isCharging: false,
          networkLatencyMs: 48,
          lastHeartbeatAt: Date.now() - 1000 * 30,
          appVersion: 'v2.5.0-prod',
        },
      ],
      printers: [
        {
          printerId: 'prn-barito-1',
          outletId: 'out-barito',
          name: 'Zjiang Bluetooth 58mm Kasir',
          connectionType: 'bluetooth',
          paperWidth: '58mm',
          status: 'out_of_paper',
          lastPrintJobAt: Date.now() - 1000 * 600,
          failedJobsCount: 4,
        },
      ],
      storage: {
        outletId: 'out-barito',
        localStorageBytes: 610000,
        estimatedQuotaBytes: 5242880,
        unSyncedTransactionsCount: 2,
        integrityOk: true,
        lastSyncAt: Date.now() - 1000 * 300,
      },
    },
    modules: {
      pos_quick_service: true,
      pos_dine_in_tables: true,
      kitchen_routing_kds: true,
      inventory_basic: true,
      inventory_recipes_hpp: true,
      multi_warehouse_transfer: false,
      batch_production_roasting: true,
      b2b_wholesale_invoicing: false,
      accurate_grade_accounting: true,
      fixed_assets: false,
      bank_reconciliation: false,
      live_excel_export: true,
      official_pdf_export: true,
    },
    emergencyMaintenance: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 35,
    updatedAt: Date.now(),
  },
  {
    id: 'tenant-bakmi-nusantara',
    slug: 'bakmi-warisan-1982',
    name: 'Bakmi Warisan 1982',
    legalName: 'PT Bakmi Nusantara Makmur',
    ownerName: 'Hendra Gunawan',
    ownerPhone: '+62 811-9988-7711',
    ownerEmail: 'hendra@bakmiwarisan.com',
    subscriptionTier: 'pro',
    billingStatus: 'past_due',
    billingCycle: 'monthly',
    monthlyFee: 799000,
    lifetimePaid: 4794000,
    autoRenew: false,
    subscriptionValidUntil: Date.now() - 1000 * 60 * 60 * 24 * 2, // 2 days past due
    maxOutlets: 2,
    maxTerminals: 4,
    healthStatus: 'critical',
    liveStoreUrl: 'https://fnb-erp.vercel.app?tenant=bakmi-warisan',
    activeOutlets: [
      {
        id: 'out-pasarbaru',
        name: 'Cabang Pasar Baru',
        code: 'PBRU',
        activeTerminalsCount: 1,
        printerHealth: 'ok',
        todayGmv: 3100000,
        todayOrdersCount: 64,
      },
    ],
    latestTelemetry: {
      devices: [
        {
          deviceId: 'dev-pbru-pos',
          name: 'POS Terminal Touch Pro 15',
          deviceType: 'pos_tablet',
          outletId: 'out-pasarbaru',
          os: 'Windows 10 IoT Enterprise',
          browser: 'Chrome 118.0',
          screenResolution: '1920x1080',
          networkLatencyMs: 310,
          lastHeartbeatAt: Date.now() - 1000 * 800,
          appVersion: 'v2.4.2-stable',
        },
      ],
      printers: [
        {
          printerId: 'prn-pbru-main',
          outletId: 'out-pasarbaru',
          name: 'Epson TM-U220 Dot Matrix Kitchen',
          connectionType: 'usb',
          paperWidth: '80mm',
          status: 'connected',
          lastPrintJobAt: Date.now() - 1000 * 900,
          failedJobsCount: 0,
        },
      ],
      storage: {
        outletId: 'out-pasarbaru',
        localStorageBytes: 3950000,
        estimatedQuotaBytes: 5242880,
        unSyncedTransactionsCount: 14,
        integrityOk: false,
        lastSyncAt: Date.now() - 1000 * 3600 * 3,
      },
    },
    modules: {
      pos_quick_service: true,
      pos_dine_in_tables: true,
      kitchen_routing_kds: true,
      inventory_basic: true,
      inventory_recipes_hpp: true,
      multi_warehouse_transfer: false,
      batch_production_roasting: false,
      b2b_wholesale_invoicing: false,
      accurate_grade_accounting: true,
      fixed_assets: false,
      bank_reconciliation: false,
      live_excel_export: true,
      official_pdf_export: true,
    },
    emergencyMaintenance: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
    updatedAt: Date.now(),
  },
  {
    id: 'tenant-fine-dining',
    slug: 'mori-dining',
    name: 'Mori Japanese Dining & Izakaya',
    legalName: 'PT Mori Boga Sukses',
    ownerName: 'Siti Rahma',
    ownerPhone: '+62 817-6655-4433',
    ownerEmail: 'rahma@moridining.com',
    subscriptionTier: 'enterprise',
    billingStatus: 'active',
    billingCycle: 'annually',
    monthlyFee: 1999000,
    lifetimePaid: 42380000,
    autoRenew: true,
    subscriptionValidUntil: Date.now() + 1000 * 60 * 60 * 24 * 320,
    maxOutlets: 5,
    maxTerminals: 15,
    healthStatus: 'healthy',
    liveStoreUrl: 'https://fnb-erp.vercel.app?tenant=mori-dining',
    activeOutlets: [
      {
        id: 'out-pik',
        name: 'Cabang PIK Avenue',
        code: 'PIK',
        activeTerminalsCount: 4,
        printerHealth: 'ok',
        todayGmv: 12400000,
        todayOrdersCount: 78,
      },
    ],
    latestTelemetry: {
      devices: [
        {
          deviceId: 'dev-pik-pos1',
          name: 'iPad Pro Kasir Depan PIK',
          deviceType: 'pos_tablet',
          outletId: 'out-pik',
          os: 'iPadOS 17.4',
          browser: 'Mobile Safari 17.4',
          screenResolution: '2732x2048',
          batteryLevel: 100,
          isCharging: true,
          networkLatencyMs: 15,
          lastHeartbeatAt: Date.now() - 1000 * 15,
          appVersion: 'v2.5.0-prod',
        },
      ],
      printers: [
        {
          printerId: 'prn-pik-80',
          outletId: 'out-pik',
          name: 'Star Micronics TSP143IV LAN',
          connectionType: 'network',
          paperWidth: '80mm',
          status: 'connected',
          lastPrintJobAt: Date.now() - 1000 * 60,
          failedJobsCount: 0,
        },
      ],
      storage: {
        outletId: 'out-pik',
        localStorageBytes: 310000,
        estimatedQuotaBytes: 5242880,
        unSyncedTransactionsCount: 0,
        integrityOk: true,
        lastSyncAt: Date.now() - 1000 * 45,
      },
    },
    modules: {
      pos_quick_service: true,
      pos_dine_in_tables: true,
      kitchen_routing_kds: true,
      inventory_basic: true,
      inventory_recipes_hpp: true,
      multi_warehouse_transfer: true,
      batch_production_roasting: false,
      b2b_wholesale_invoicing: true,
      accurate_grade_accounting: true,
      fixed_assets: true,
      bank_reconciliation: true,
      live_excel_export: true,
      official_pdf_export: true,
    },
    emergencyMaintenance: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 120,
    updatedAt: Date.now(),
  },
  {
    id: 'tenant-grab-booth',
    slug: 'kopi-booth-mrt',
    name: 'Kopi Booth Express Sudirman',
    legalName: 'Kopi Booth Mandiri',
    ownerName: 'Arif Hidayat',
    ownerPhone: '+62 856-7788-9900',
    ownerEmail: 'arif@kopibooth.id',
    subscriptionTier: 'starter',
    billingStatus: 'trial',
    billingCycle: 'monthly',
    monthlyFee: 299000,
    lifetimePaid: 0,
    autoRenew: false,
    subscriptionValidUntil: Date.now() + 1000 * 60 * 60 * 24 * 12,
    maxOutlets: 1,
    maxTerminals: 1,
    healthStatus: 'offline',
    liveStoreUrl: 'https://fnb-erp.vercel.app?tenant=kopi-booth',
    activeOutlets: [
      {
        id: 'out-mrt',
        name: 'Kios MRT Dukuh Atas',
        code: 'MRT',
        activeTerminalsCount: 0,
        printerHealth: 'offline',
        todayGmv: 0,
        todayOrdersCount: 0,
      },
    ],
    latestTelemetry: {
      devices: [
        {
          deviceId: 'dev-mrt-pos',
          name: 'Xiaomi Pad 6 Kios',
          deviceType: 'pos_tablet',
          outletId: 'out-mrt',
          os: 'Android 13.0',
          browser: 'Chrome 120.0',
          screenResolution: '2880x1800',
          batteryLevel: 15,
          isCharging: false,
          networkLatencyMs: 0,
          lastHeartbeatAt: Date.now() - 1000 * 60 * 60 * 18,
          appVersion: 'v2.5.0-prod',
        },
      ],
      printers: [
        {
          printerId: 'prn-mrt-58',
          outletId: 'out-mrt',
          name: 'Mini Thermal Bluetooth 58mm',
          connectionType: 'bluetooth',
          paperWidth: '58mm',
          status: 'disconnected',
          lastPrintJobAt: Date.now() - 1000 * 60 * 60 * 20,
          failedJobsCount: 1,
        },
      ],
      storage: {
        outletId: 'out-mrt',
        localStorageBytes: 120000,
        estimatedQuotaBytes: 5242880,
        unSyncedTransactionsCount: 0,
        integrityOk: true,
        lastSyncAt: Date.now() - 1000 * 60 * 60 * 18,
      },
    },
    modules: {
      pos_quick_service: true,
      pos_dine_in_tables: false,
      kitchen_routing_kds: false,
      inventory_basic: true,
      inventory_recipes_hpp: false,
      multi_warehouse_transfer: false,
      batch_production_roasting: false,
      b2b_wholesale_invoicing: false,
      accurate_grade_accounting: false,
      fixed_assets: false,
      bank_reconciliation: false,
      live_excel_export: false,
      official_pdf_export: true,
    },
    emergencyMaintenance: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    updatedAt: Date.now(),
  },
]

export const INITIAL_REMOTE_LOGS: RemoteLogEntry[] = [
  {
    id: 'log-err-001',
    tenantId: 'tenant-bakmi-nusantara',
    outletId: 'out-pasarbaru',
    outletName: 'Cabang Pasar Baru',
    timestamp: Date.now() - 1000 * 60 * 14,
    level: 'fatal',
    message: 'DOMException QuotaExceededError: Setting key "fnb_erp_v1_orders" exceeded available local quota.',
    stackTrace: `QuotaExceededError: Setting the value of 'fnb_erp_v1_orders' exceeded the quota.
    at saveStoredData (lib/store/storage.ts:45:24)
    at handleOrderComplete (app/page.tsx:412:9)
    at onClick (components/PosTab.tsx:3022:15)`,
    sourceModule: 'LocalStorage Engine (POS Checkout)',
    deviceInfo: 'Windows 10 Touch Pro 15 (Chrome 118.0)',
    context: {
      storageUsedBytes: 3950000,
      stuckOrdersCount: 14,
      affectedBillNumber: 'ORD-20261008-042',
    },
    resolved: false,
  },
  {
    id: 'log-warn-002',
    tenantId: 'tenant-kopi-artisan',
    outletId: 'out-barito',
    outletName: 'Cabang Barito',
    timestamp: Date.now() - 1000 * 60 * 8,
    level: 'error',
    message: 'ESC/POS Printer Error: Hardware paper status sensor reported out-of-paper during receipt cut.',
    stackTrace: `PrinterHardwareException: Paper out signal high (Status byte: 0x1E)
    at printThermalReceiptViaIframe (lib/hardware/printer.ts:94:12)
    at handlePrintBill (components/PosTab.tsx:1890:7)`,
    sourceModule: 'ESC/POS Hardware Driver',
    deviceInfo: 'iPad 10th Gen (Safari 17.2) · Bluetooth Zjiang 58mm',
    context: {
      printerModel: 'Zjiang 58mm',
      failedAttempts: 4,
      lastPrintedOrder: 'ORD-TITIK-088',
    },
    resolved: false,
  },
  {
    id: 'log-warn-003',
    tenantId: 'org-resto',
    outletId: 'out-senopati',
    outletName: 'Cabang Senopati',
    timestamp: Date.now() - 1000 * 60 * 25,
    level: 'warn',
    message: 'Slow KDS Web Audio latency: Chime buffer decode took 320ms due to high CPU load.',
    sourceModule: 'KDS Audio Service',
    deviceInfo: 'Android 13.0 TV Display (Chrome 122.0)',
    context: {
      audioContextLatency: 320,
      activeTicketCount: 9,
    },
    resolved: true,
  },
  {
    id: 'log-info-004',
    tenantId: 'org-resto',
    outletId: 'out-dago',
    outletName: 'Cabang Dago',
    timestamp: Date.now() - 1000 * 60 * 42,
    level: 'info',
    message: 'Shift closing report generated and synchronized successfully by Kasir Dago.',
    sourceModule: 'Cashier Shift Reconcile',
    deviceInfo: 'Samsung Tab S8 (Chrome 124.0)',
    context: {
      cashActual: 3200000,
      difference: 0,
      closedBy: 'usr-dago-kasir',
    },
    resolved: true,
  },
]

export const INITIAL_STAFF_AUDIT_LOGS: StaffAuditLog[] = [
  {
    id: 'audit-001',
    staffEmail: 'ops@hallogroup.id',
    staffName: 'Akmal Irsyad (Lead Ops)',
    action: 'INVOICE_GENERATED',
    targetTenantId: 'tenant-kopi-artisan',
    targetTenantName: 'Kopi Titik Temu',
    details: 'Menerbitkan faktur INV/2026/10/003 (Rp 949.000) untuk perpanjangan Pro + 1 Extra Cabang Kemang.',
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: 'audit-002',
    staffEmail: 'support@hallogroup.id',
    staffName: 'Finance Hallo Group',
    action: 'SUBSCRIPTION_EXTENDED',
    targetTenantId: 'org-resto',
    targetTenantName: 'Nusantara Bistro',
    details: 'Memperpanjang masa aktif lisensi Enterprise hingga 180 hari ke depan paska settlement invoice.',
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 28,
  },
]

export const INITIAL_PROVISIONING_REQUESTS: ProvisioningRequest[] = [
  {
    id: 'req-001',
    storeName: 'Sate Khas Senayan Express',
    legalName: 'PT Kuliner Nusantara Sate',
    ownerName: 'Bambang Soedirgo',
    ownerPhone: '+62 812-4455-6677',
    ownerEmail: 'bambang@satesenayan.id',
    requestedTier: 'enterprise',
    requestedOutlets: 4,
    billingCycle: 'annually',
    notes: 'Klien inbound dari website Hallo Group. Membutuhkan integrasi 4 cabang di Jakarta Selatan.',
    status: 'pending_review',
    submittedAt: Date.now() - 1000 * 60 * 120,
  },
  {
    id: 'req-002',
    storeName: 'Kopi Kenangan Senja (Booth)',
    ownerName: 'Reza Pahlevi',
    ownerPhone: '+62 878-1122-8899',
    ownerEmail: 'reza@kopisenja.com',
    requestedTier: 'starter',
    requestedOutlets: 1,
    billingCycle: 'monthly',
    notes: 'Mendaftar via landing page self-registration gratis trial 14 hari.',
    status: 'pending_review',
    submittedAt: Date.now() - 1000 * 60 * 340,
  },
]
